---
# All the tasks that require sudo
- name: Configure Debian host
  gather_facts: false
  hosts: all
  tasks:
    - name: Ensure group "plugdev" exists
      become: true
      ansible.builtin.group:
        name: plugdev
        state: present

    - name: Add user to plugdev group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: plugdev
        append: yes

    - name: Set up udev rules
      become: true
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/90-co2mini.rules"
        dest: "/etc/udev/rules.d/"
        owner: "root"
        group: "root"
        mode: '0644'
      register: udev_rules

    - name: Reload udev rules
      become: true
      ansible.builtin.command:
        cmd: "udevadm control --reload-rules"
      when: udev_rules.changed

    - name: Trigger udev rules
      become: true
      ansible.builtin.command:
        cmd: "udevadm trigger"
      when: udev_rules.changed

    - name: Install MariaDB client libraries
      become: true
      ansible.builtin.apt:
        pkg:
          - libmariadb3
          - libmariadb-dev

    - name: Enable lingering for user (to allow user-mode systemd services to run at boot)
      become: true
      ansible.builtin.command:
        cmd: "loginctl enable-linger {{ ansible_user }}"
        creates: "/var/lib/systemd/linger/{{ ansible_user }}"
